name: CI/CD - Android Mobile Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-android:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    env:
      PLATFORM: android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Nexus 6
          disable-animations: true
          script: |
            echo "Waiting for emulator to boot..."
            adb wait-for-device
            boot_status=""
            until [[ "$boot_status" == "1" ]]; do
              boot_status=$(adb -e shell getprop sys.boot_completed | tr -d '\r')
              echo "Boot status: $boot_status"
              sleep 5
            done
            echo "Emulator booted."

      - name: Restart ADB server (in case of device offline)
        run: |
          adb kill-server
          adb start-server
          adb devices

      - name: Start Appium Server
        run: |
          npm run appium & npx wait-on http://localhost:4723/status

      - name: Run Android tests
        run: npm run test:android

      - name: Generate Allure Report
        if: always()
        run: npm run report
        continue-on-error: true

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-android
          path: reports/allure-report
