name: CI/CD - Android with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-android:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    services:
      android-emulator:
        image: saucelabs/stt/android-emulator:latest
        ports:
          - 4723:4723
        options: >-
          --privileged
          --shm-size=2g
          --device /dev/kvm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Wait for Appium to be ready
        run: npx wait-on http://localhost:4723/wd/hub/status

      - name: Run Android tests
        run: npm run test:android

      - name: Generate Allure Report
        if: always()
        run: npm run report
        continue-on-error: true

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-android
          path: reports/allure-report
