name: iOS tests on BrowserStack

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-browserstack-ios:
    runs-on: macos-latest
    timeout-minutes: 40

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      PLATFORM: ios

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run iOS tests on BrowserStack
        run: npx wdio run ./config/wdio.browserstack.conf.mjs

      - name: Generate Allure Report
        if: always()
        run: npm run report || echo "Allure report failed but tests already ran"
        continue-on-error: true

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-ios
          path: reports/allure-report
